pub const HELP_ENTRIES: &[(&str, &str)] = &[
    ("", ""),
    ("", "── GLOBAL ──"),
    ("F1 or ?", "Toggle this help"),
    ("Ctrl+A", "Toggle AI assistant"),
    ("Ctrl+C", "Quit without output"),
    ("Enter", "Output filtered JSON and exit"),
    ("Ctrl+Q", "Output query string only and exit"),
    ("Shift+Tab", "Switch focus (Input / Results)"),
    ("q", "Quit (in Normal mode or Results pane)"),
    ("", ""),
    ("", "── INPUT: INSERT MODE ──"),
    ("Esc", "Switch to Normal mode"),
    ("↑/Ctrl+R", "Open history popup"),
    ("Ctrl+P/N", "Previous/Next query in history"),
    ("Ctrl+D/U", "Scroll results half page down/up"),
    ("", ""),
    ("", "── INPUT: NORMAL MODE ──"),
    ("i/a/I/A", "Enter Insert mode"),
    ("h/l", "Move cursor left/right"),
    ("0/^/$", "Jump to start/end of line"),
    ("w/b/e", "Word navigation"),
    ("f/F/t/T", "Find/till char forward/backward"),
    (";/,", "Repeat/reverse last char search"),
    ("x/X", "Delete character"),
    ("dd/D", "Delete line/to end"),
    ("dw/cw/ciw", "Delete/change word (operators)"),
    ("df/dt/cf/ct", "Delete/change to/till char (operators)"),
    ("di\"/ci\"/da\"/ca\"", "Delete/change quotes (text objects)"),
    ("di(/ci(/da(/ca(", "Delete/change parens (text objects)"),
    ("di|/ci|/da|/ca|", "Delete/change pipe segment"),
    ("u", "Undo"),
    ("Ctrl+R", "Redo"),
    ("Ctrl+D/U", "Scroll results half page down/up"),
    ("", ""),
    ("", "── AUTOCOMPLETE (when visible) ──"),
    ("Up/Down", "Navigate suggestions"),
    ("Tab", "Accept suggestion"),
    ("Esc", "Dismiss"),
    ("", ""),
    ("", "── RESULTS PANE ──"),
    ("j/k/↑/↓", "Scroll line by line"),
    ("J/K", "Scroll 10 lines"),
    ("h/l/←/→", "Scroll column by column"),
    ("H/L", "Scroll 10 columns"),
    ("0/^", "Jump to left edge"),
    ("$", "Jump to right edge"),
    ("g/Home", "Jump to top"),
    ("G/End", "Jump to bottom"),
    ("Ctrl+D/U", "Half page down/up"),
    ("PageDown/Up", "Half page down/up"),
    ("", ""),
    ("", "── SEARCH IN RESULTS ──"),
    ("Ctrl+F", "Open search (from any pane)"),
    ("/", "Open search (from Results pane)"),
    ("Enter", "Confirm search"),
    ("n/Enter", "Next match"),
    ("N/Shift+Enter", "Previous match"),
    ("Ctrl+F or /", "Re-enter edit mode"),
    ("Esc", "Close search"),
    ("", ""),
    ("", "── HISTORY POPUP ──"),
    ("Up/Down", "Navigate entries"),
    ("Type", "Fuzzy search filter"),
    ("Enter/Tab", "Select entry and close"),
    ("Esc", "Close without selecting"),
    ("", ""),
    ("", "── ERROR OVERLAY ──"),
    ("Ctrl+E", "Toggle error details"),
    ("", ""),
    ("", "── AI ASSISTANT ──"),
    ("Ctrl+A", "Toggle AI assistant"),
    ("Alt+1-5", "Apply AI suggestion (direct)"),
    ("Alt+↑↓/j/k", "Navigate suggestions"),
    ("Enter", "Apply selected suggestion"),
];

pub const HELP_FOOTER: &str = "j/k: scroll | g/G: top/bottom | F1/q/?: close";
